apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: driftsiren
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: ghcr.io/example/driftsiren-backend:latest
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: REDIS_URL
          value: redis://redis:6379/0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: driftsiren
spec:
  selector: { app: backend }
  ports:
  - port: 8000
    targetPort: 8000
